version: 2.1

executors:
  main:
    docker:
      - image: cimg/base:current
      - image: docker.io/bitnami/postgresql:12.6.0
        environment:
          POSTGRESQL_DATABASE: wiki
          POSTGRESQL_USERNAME: Free
          POSTGRESQL_PASSWORD: Willy

jobs:
  build:
    executor: main
    steps:
      - checkout
      - run:
          name: Wait for DB to be ready
          command: |
            dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Insert records
          command: |
            export POSTGRESQL_PASSWORD="Willy"
            psql -h 127.0.0.1 -p 5432 -d wiki -U Free -f schema.sql
      - run:
          name: Check records
          command: |
            export POSTGRESQL_PASSWORD="Willy"
            psql -h 127.0.0.1 -p 5432 -d wiki -U Free -c "SELECT * FROM characters;"
