version: 2.1

executors:
  bitnami:
    docker:
      - image: cimg/base:current
      - image: docker.io/bitnami/postgresql:12.6.0
        environment:
          POSTGRESQL_DATABASE: wiki
          POSTGRESQL_PASSWORD: Willy
  custom:
    docker:
      - image: cimg/base:current
      - image: cciserver.azurecr.io/server-postgres:12.16.32-dc3b53b
        auth:
          username: $ACR_USERNAME
          password: $ACR_PASSWORD
        environment:
          POSTGRESQL_DATABASE: wiki
          POSTGRESQL_PASSWORD: Willy
  official:
    docker:
      - image: cimg/base:current
      - image: postgres:12.6
        environment:
          POSTGRES_DB: wiki
          POSTGRES_PASSWORD: Willy
jobs:
  build:
    parameters:
      exec:
        type: string
    executor: << parameters.exec >>
    environment:
      PGPASSWORD: Willy
    steps:
      - checkout
      - run:
          name: Wait for DB to be ready
          command: |
            dockerize -wait tcp://localhost:5432 -timeout 1m

            N=20
            while [ $N -gt 0 ]
            do
              if $(psql -h 127.0.0.1 -p 5432 -d wiki -U postgres -c "/* ping */ SELECT 1" > /dev/null); then
                echo "Connected to PostgreSQL!"
                exit 0
              fi
              echo "Not connected; retrying"
              N=$(( $N - 1 ))
              sleep 1
            done
            exit 1
      - run: sleep 3
      - run:
          # From Postgres >= v12, JIT is on by default.
          # https://www.postgresql.org/docs/current/runtime-config-query.html#GUC-JIT
          name: Check JIT
          command: |
            # SELECT pg_jit_available() will fail for cciserver.azurecr.io/server-postgres:12.16.32-dc3b53b container
            # We will see the following error:
            #     could not load library "/opt/bitnami/postgresql/lib/llvmjit.so": libLLVM-11.so.1: cannot open shared object file: No such file or directory
            psql -h 127.0.0.1 -p 5432 -d wiki -U postgres -c "SHOW jit;"
            psql -h 127.0.0.1 -p 5432 -d wiki -U postgres -c "SELECT pg_jit_available();"
      - run:
          name: Insert records
          when: always
          command: |
            psql -h 127.0.0.1 -p 5432 -d wiki -U postgres -f schema.sql
      - run:
          name: Check records
          when: always
          command: |
            psql -h 127.0.0.1 -p 5432 -d wiki -U postgres -c "SELECT COUNT(*) FROM characters;"
      - run:
          # see https://www.postgresql.org/docs/current/jit-decision.html
          name: test trigger JIT via queries
          when: always
          command: |
            # run a SQL query requiring high computation that should trigger JIT compilation
            psql -h 127.0.0.1 -p 5432 -d wiki -U postgres -c "EXPLAIN ANALYZE SELECT AVG(c1.strength * c2.strength) FROM characters AS c1 CROSS JOIN characters AS c2;"

            # lower JIT_ABOVE_COST to 0 so JIT should be used, just in case
            psql -h 127.0.0.1 -p 5432 -d wiki -U postgres -c "ALTER DATABASE wiki SET jit_above_cost = 0;"
            # NOTE: if pg_jit_available() = false, JIT will not be used no matter what.
            psql -h 127.0.0.1 -p 5432 -d wiki -U postgres -c "EXPLAIN ANALYZE SELECT AVG(c1.strength * c2.strength) FROM characters AS c1 CROSS JOIN characters AS c2;"
      - when:
          condition:
            equal:
              - 'custom'
              - << parameters.exec >>
          steps:
            - run:
                name: set JIT_ABOVE_COST to be -1 (same as JIT off)
                when: always
                command: |
                  # disable JIT via setting JIT_ABOVE_COST = -1
                  psql -h 127.0.0.1 -p 5432 -d wiki -U postgres -c "ALTER DATABASE SET jit_above_cost = -1;"
                  psql -h 127.0.0.1 -p 5432 -d wiki -U postgres -c "EXPLAIN ANALYZE SELECT AVG(c1.strength * c2.strength) FROM characters AS c1 CROSS JOIN characters AS c2;"
            - run:
                name: set JIT off
                when: always
                command: |
                  # disable JIT
                  psql -h 127.0.0.1 -p 5432 -d wiki -U postgres -c "ALTER DATABASE wiki SET jit = off;"
                  psql -h 127.0.0.1 -p 5432 -d wiki -U postgres -c "EXPLAIN ANALYZE SELECT AVG(c1.strength * c2.strength) FROM characters AS c1 CROSS JOIN characters AS c2;"
workflows:
  main:
    jobs:
      - build:
          matrix:
            parameters:
              exec:
                - bitnami
                - custom
                - official
