version: 2.1

executors:
  main:
    docker:
      - image: cimg/aws:2024.03

jobs:
  build:
    executor: main
    environment:
      POSTGRES_DB: wiki
      POSTGRES_USER: Free
      POSTGRES_PASSWORD: Willy
      PGPASSWORD: Willy
    steps:
      - setup_remote_docker
      - checkout
      - run: docker-compose up -d
      - run: docker ps
      - run: docker network ls
      - run:
          name: find main Docker network of pause container
          command: |
            CNTR_ID_MAIN=$(docker ps --filter="ancestor=public.ecr.aws/eks-distro/kubernetes/pause:3.6" -q)
            echo "export CNTR_NETWORK_MAIN=$(docker container inspect $CNTR_ID_MAIN | jq -r '.[0].NetworkSettings.Networks|map(select(.Aliases))|.[0].NetworkID')" >> $BASH_ENV
      - run:
          name: connect sidecar containers from Compose to main network
          command: |
            echo $CNTR_NETWORK_MAIN
            COMPOSE_CNTR_LIST=$(docker-compose ps -q)
            for cntr in $COMPOSE_CNTR_LIST; do
              docker network connect $CNTR_NETWORK_MAIN $cntr
            done
      - run:
          name: Wait for DB to be ready
          # NOTE: i refer to the container name (db) since that is the DNS record
          command: |
            dockerize -wait tcp://db:5432 -timeout 1m
      - run:
          name: Wait for Redis to be ready
          # NOTE: i refer to the container name (redis) since that is the DNS record
          command: |
            dockerize -wait tcp://redis:6379 -timeout 1m
      - run:
          name: Insert records
          command: |
            psql -h db -p 5432 -d wiki -U Free -f schema.sql
      - run:
          name: Check records
          command: |
            psql -h db -p 5432 -d wiki -U Free -c "SELECT * FROM characters;"
